const char* author =
"<html>"
"<head>"
    "<title>Particle Web Server - Autor</title>"
"</head>"
"<body>"
    "<ul>"
        "<li><a href='/'>Home</a></li>"
        "<li><a href='/more'>More</a></li>"
        "<li><a href='/author'>Author</a></li>"
    "</ul>"
    "<h1>David Gatti</h1>"
    "<p>Follow David on <a href='https://twitter.com/dawidgatti' target='_blank'>Twitter</a></p>"
"</body>"
"</html>"
;
