const char* home =
"<html>"
"<head>"
    "<title>Particle Web Server</title>"
    "<meta http-equiv='refresh' content='1'>"
"</head>"
"<body>"
    "<ul>"
        "<li><a href='/'>Home</a></li>"
        "<li><a href='/more'>More</a></li>"
        "<li><a href='/author'>Author</a></li>"
    "</ul>"
    "<h1>Hello World</h1>"
    "<p>I'm a simple Particle server. The time is: <b>{time}</b>, and my IP address is: <b>{ip}</b>.</p>"
"</body>"
"</html>"
;
